class TermStyle:
    black    = '\x1b[30m'
    white    = '\x1b[37m'
    gray     = '\x1b[90m'
    red      = '\x1b[31m'
    lite_red = '\x1b[91m'
    green    = '\x1b[32m'
    yellow   = '\x1b[33m'
    blue     = '\x1b[34m'
    magenta  = '\x1b[35m'
    cyan     = '\x1b[36m'
    reset    = '\x1b[0m'

    bold      = '\x1b[1m'
    italic    = '\x1b[3m'
    undrline  = '\x1b[4m'
    strkthru  = '\x1b[9m'
    off       = '\x1b[m'


    bg_black    = '\x1b[40m'
    bg_red      = '\x1b[41m'
    bg_green    = '\x1b[42m'
    bg_yellow   = '\x1b[43m'
    bg_blue     = '\x1b[44m'
    bg_magenta  = '\x1b[45m'
    bg_cyan     = '\x1b[46m'
    bg_litegray = '\x1b[47m'
